services:
  db:
    build:
      context: ./backend/db
    container_name: myapp-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
          

  backend:
    build:
      context: ./backend
    container_name: myapp-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
       context: ./frontend
    container_name: myapp-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
