services:
  backend:
    build:
      context: ./backend
    image: quizzy-backend      
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - PROFESSOR_SECRET_KEY=${PROFESSOR_SECRET_KEY}
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: http://52.28.16.232
    image: quizzy-frontend
    environment:
      VITE_BACKEND_URL: http://52.28.16.232
    ports:
      - "80:80"
    depends_on:
      - backend
