services:
  backend:
    image: public.ecr.aws/w9j1e0m5/quizzy/backend:latest
    container_name: backend
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3000:3000"

  frontend:
    image: public.ecr.aws/w9j1e0m5/quizzy/frontend:latest
    container_name: frontend
    environment:
      VITE_BACKEND_URL: http://backend:3000
    ports:
      - "80:80"
    depends_on:
      - backend