name: Java CI with Docker (Backend)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            maven-

      - name: Run tests with Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from backend
