name: Java CI with Docker (Backend)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start services
        run: docker compose up -d myapp-db

      - name: Build app container
        run: docker compose build myapp-backend

      - name: Run tests
        run: docker compose run --rm myapp-backend mvn verify

      - name: Tear down
        if: always()
        run: docker-compose down
