name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set environment variables
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/mydb" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=myuser" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=mypass" >> $GITHUB_ENV

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.override.yml up -d --build

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Maven tests with coverage
        working-directory: ./backend
        run: mvn test jacoco:report

      - name: Publish Test Results (JUnit)
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: './backend/target/surefire-reports/TEST-*.xml'
          require_tests: true

      - name: Upload JaCoCo coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./backend/target/site/jacoco

      - name: Extract Coverage Percentage
        run: |
          LINE_COVERED=$(grep -oP '(?<=<counter type="LINE" missed=")[0-9]+' ./backend/target/site/jacoco/jacoco.xml)
          LINE_TOTAL=$(grep -oP '(?<=<counter type="LINE" missed=")[0-9]+' ./backend/target/site/jacoco/jacoco.xml | paste -sd+ - | bc)
          LINE_COVERED=$(grep -oP '(?<=covered=")[0-9]+' ./backend/target/site/jacoco/jacoco.xml | paste -sd+ - | bc)
          PERCENTAGE=$(echo "scale=2; $LINE_COVERED * 100 / $LINE_TOTAL" | bc)
          echo "Code Coverage: $PERCENTAGE%"
          echo "COVERAGE_PERCENTAGE=$PERCENTAGE" >> $GITHUB_ENV

      - name: Stop Docker Compose
        if: always()
        run: docker compose -f docker-compose.override.yml down
